### ISSUE TITLE
This should say event. afaik

### ISSUE THREAD

**Issue by Jlobblet** [davidjrichardson/warwick_gg#9]
https://github.com/davidjrichardson/warwick_gg/blob/f029381846599ef564f3c976fb6ef5321cc88805/dashboard/templates/dashboard/dashboard_index.html#L76

**Comment by Toby-Lawrance** [comment]
Jeez, how could such a mistake slip through. So easy to test

**Comment by RVHowarth** [comment]
Merging #10 should fix the issue.
